let Sammy = {
  name: "Sammy Pinto",
  references: [
    {
      name: "Stephen Potter",
      location: "Freda",
      role: "Head of AV Tech",
      email: "s.potter.promo@gmail.com",
      number: "0421 761 305"
    },
    {
      name: "Michael Mclennan",
      location: "Sydney Film School",
      role: "Head of Film School",
      email: "mclennan.michael@gmail.com",
      number: "0432 085 370"
    }
  ],
  contacts: {
    address: "St Peters, 2044",
    city: "Sydney NSW",
    number: "0404 858 205",
    email: "sammyp.film@gmail.com",
    instagram: [
      {
        name:" @ripsammypinto2016",
        link: "https://www.instagram.com/ripsammypinto2016/"
      },
      {
        name: "@minipinto",
        link: "https://www.instagram.com/minipinto/"
      },
      {
        name: "@crackflowerproductions",
        link: "https://www.instagram.com/crackflowerproductions/"
      }
    ],
    linkedin: "someurl"
  },
  filmRoles: [
    "Director",
    "DOP",
    "Camera Operator",
    "Camera Assistant",
    "Gaffer",
    "Best Boy",
    "Runner",
  ],
  awards: [
    "Best Cinematographer: Diploma of Screen and Media Part 2 - Sammy Pinto ‘Jesus Piece’",
    "Most Provocative Film - ‘WTF TV PRESENTS: SASHA’",
    "Duke of Edinburgh Scheme - Bronze, Silver and Gold",
    "Employee of the month - Hoyts",
    "The Scarf Foundation Award for Commitments to the School Environment",
    "Received many awards/trophies in sporting achievements",
  ],
  qualifications: [
    "RSA",
    "RCG",
    "Full Drivers Licence",
  ],
  experiences: [
    {
      title: "Freelance",
      location: "Sydney",
      role: "Photography, Film, Directing, Producing, Camera Assisting and Sound",
      date: "January 2014 - Present",
    },
    {
      title: "Frankie's Pizza",
      location: "Sydney",
      role: "Barback",
      date: "April 2019 - Present",
    },
    {
      title: "Fredas",
      location: "Chippendale",
      role: "AV tech and Barback",
      date: "April 2019 - November 2020",
    },
    {
      title: "The George",
      location: "Waterloo",
      role: "Bartender, Gaming Attendant and Food runner",
      date: "March 2019 - May 2019",
    },
    {
      title: "Hoyts",
      location: "Broadway",
      role: "Usher, Boxsale and CandyBar",
      date: "January 2018 - April 2019",
    },
    {
      title: "Black Comedy",
      location: "ABC",
      role: "Camera Assistant",
      date: "2018",
    },
    {
      title: "Sydney Underground Film Festival",
      location: " Marrickville",
      role: "Usher and Merch",
      date: "September 14th - 20th 2017",
    },
    {
      title: "Tropfest",
      location: "Parramatta",
      role: "Volunteer",
      date: "2016",
    },
    {
      title: "Anthony Khoury Photography",
      location: "Lane Cove",
      role: "Work Experience",
      date: "July 14th - 18th 2014",
    },
    {
      title: "Tara Anglican School For Girls",
      location: "North Parramatta",
      role: "School Photographer",
      date: "2012 - 2016",
    },
  ],
  educations: [
{
      title: "Sydney Film School",
      location: "Green Square",
      qualifications: "Diploma of Screen and Media, Advanced Certificate in Film Sound ",
      date: "February 2017 - December 2018",
},
{
      title: "Tara Anglican School For Girls",
      location: "North Parramatta",
      qualifications: "Kindergarten - Year 12 HSC",
      date: "March 2004 - December 2016",
},
],
  projects: [
    {
      title: "Ziggy Ramo performs 'APRIL 25th', FBI Radio SMAC Awards",
      date: "2020",
      role: "Camera Operator",
      description: "Live performance at FBI Radio",
      video: "https://youtu.be/CtYowrBA-aI",
      dateOrder: "1/3/2021",
    },
    {
      title: "Dogma, Reformation",
      date: "2020",
      role: "Camera Operator",
      description: "Music Video",
      video: "https://youtu.be/0_APKCN6c8E ",
      dateOrder: "1/5/2020",
    },
    {
      title: "The Flower (post production) ",
      date: "2020",
      role: "Camera Assistant and Camera Operator",
      description: "Short film",
      dateOrder: "1/1/2020",
    },
    {
      title: "Rosa Racer, Sober [music video]",
      date: "2021",
      role: "Director",
      description: "Music Video",
      dateOrder: "2/1/2021",
    },
    {
      title: "Hayley Mary, Live show 2020 (Post Production)",
      date: "2020",
      role: "Camera Operator",
      description: "Live show recording at Paddo RSL",
      dateOrder: "3/1/2020",
    },
    {
      title: "The Melodrones, I’ll belong to you [Live Performance]",
      date: "2020",
      role: "Camera Operator",
      description: "Live set recording at Paddo RSL",
      video: "https://www.instagram.com/tv/CIfFCmsBLBs/?hl=en",
      dateOrder: "4/1/2020",
    },
    {
      title: "Hayley Mary, The Chain [Nude Version]",
      date: "2020",
      role: "Camera Operator ",
      description: "Music Video",
      video: "https://youtu.be/oXBfKFxOq1o ",
      dateOrder: "5/1/2020",
    },
    {
      title: "DMA’S, Round & Around [Official Video]",
      date: "2020",
      role: "Production Assistant and Camera Operator",
      description: "Music Video",
      video: "https://youtu.be/Qh-pJHglDdk",
      dateOrder: "6/1/2020",
    },
    {
      title: "Only if you're lucky (Post Production)",
      date: "2019",
      role: "Director and Actor",
      description: "Short film ",
      dateOrder: "1/1/2019",
    },
    {
      title: "Havas, Everyday",
      date: "2019",
      role: "Camera Operator",
      description: "Season II Episode 5 - Carpark",
      video: "https://youtu.be/tswYTMagdW4",
      dateOrder: "2/1/2019",
    },
    {
      title: "Nostalgia",
      date: "2019",
      role: "2nd AC",
      description: "Short film",
      dateOrder: "3/1/2019",
    },
    {
      title: "Pendulum",
      date: "2019",
      role: "2nd AC/2nd Camera Operator/Design Assistant",
      description: "Short film",
      dateOrder: "4/1/2019",
    },
    {
      title: "Bare Intimacy",
      date: "2019",
      role: "2nd AC/Gaffer",
      description: "Short film",
      dateOrder: "5/1/2019",
    },
    {
      title: "Projection",
      date: "2019",
      role: "2nd AC/Unit B Camera Operator/Sound Recordist",
      description: "Short film",
      dateOrder: "6/1/2019",
    },
    {
      title: "Detached",
      date: "2019",
      role: "Sound Recordist/Sound designer",
      description: "Short film",
      dateOrder: "7/1/2019",
    },
    {
      title: "Rosemary’s Way",
      date: "2019",
      role: "Camera Assistant",
      description: "Documentary Feature film",
      dateOrder: "8/1/2019",
    },
    {
      title: "Pananampalataya",
      date: "2018",
      role: "2nd AC",
      description: "Short film",
      dateOrder: "1/1/2018",
    },
    {
      title: "Backstage Backstab",
      date: "2018",
      role: "DOP",
      description: "Short film",
      dateOrder: "2/1/2018",
    },
    {
      title: "Claire",
      date: "2018",
      role: "DOP",
      description: "Short film",
      dateOrder: "3/1/2018",
    },
    {
      title: "Garbvati Sannata",
      date: "2018",
      role: "2nd AC",
      description: "Short film",
      dateOrder: "4/1/2018",
    },
    {
      title: "The Last Night of Summer",
      date: "2018",
      role: "Gaffer",
      description: "Short film",
      dateOrder: "5/1/2018",
    },
    {
      title: "Bystander",
      date: "2018",
      role: "2nd AC",
      description: "Short film",
      dateOrder: "6/1/2018",
    },
    {
      title: "Prehension",
      date: "2018",
      role: "Sound recordist/Sound designer/Sound mixer",
      description: "Short film",
      dateOrder: "7/1/2018",
    },
    {
      title: "Mawar",
      date: "2018",
      role: "2nd AC",
      description: "Short film",
      dateOrder: "8/1/2018",
    },
    {
      title: "Barnett",
      date: "2018",
      role: "2nd AC",
      description: "Short film",
      dateOrder: "9/1/2018",
    },
    {
      title: "Cosmic Dancer",
      date: "2018",
      role: "2nd AC",
      description: "Short film",
      dateOrder: "1/2/2018",
    },
    {
      title: "Greenery Interlude",
      date: "2018",
      role: "Sound recordist/Sound designer/Sound mixer",
      description: "Short film",
      dateOrder: "2/2/2018",
    },
    {
      title: "AAI: Abnormal Australian Investigations",
      date: "2018",
      role: "2nd AC",
      description: "Short film",
      dateOrder: "3/2/2018",
    },
    {
      title: "The Harbinger of Apollo",
      date: "2018",
      role: "Best boy",
      description: "Short film",
      dateOrder: "4/2/2018",
    },
    {
      title: "Against All Odds",
      date: "2018",
      role: "Sound recordist/Sound designer/Sound mixer",
      description: "Short film",
      dateOrder: "5/2/2018",
    },
    {
      title: "Bad Math, Oceans",
      date: "2018",
      role: "Gaffer",
      description: "Music Video",
      video: "https://vimeo.com/299999250",
      dateOrder: "6/2/2018",
    },
    {
      title: "Toyboy",
      date: "2018",
      role: "Gaffer/2nd AC",
      description: "Feature film",
      dateOrder: "7/2/2018",
    },
    {
      title: "Rackett, Alive",
      date: "2018",
      role: "Gaffer",
      description: "Music video",
      video: "https://youtu.be/8KYJ0mPIbxM",
      dateOrder: "8/2/2018",
    },
    {
      title: "Ballet De La Nuit",
      date: "2018",
      role: "Stills Photographer/Best Boy/Runner",
      description: "Feature film",
      dateOrder: "9/2/2018",
    },
    {
      title: "Harper's Bazaar India, Vivid",
      date: "2018",
      role: "BTS",
      description: "Fashion shoot",
      dateOrder: "1/3/2018",
    },
    {
      title: "Action stars audition",
      date: "2017",
      role: "DOP",
      description: "Tv show",
      dateOrder: "1/1/2017",
    },
    {
      title: "Fractured",
      date: "2017",
      role: "2nd AC",
      description: "Short film",
      dateOrder: "2/1/2017",
    },
    {
      title: "The List",
      date: "2017",
      role: "Sound Recordist",
      description: "2017",
      dateOrder: "3/1/2017",
    },
    {
      title: "Missing girl",
      date: "2017",
      role: "Runner",
      description: "Funding for feature film",
      dateOrder: "4/1/2017",
    },
    {
      title: "In transit",
      date: "2017",
      role: "Producer/2nd AC/Design Assistant/Sound Recordist",
      description: "Short film",
      dateOrder: "5/1/2017",
    },
    {
      title: "Jesus Piece",
      date: "2017",
      role: "DOP",
      description: "Short film",
      video: "https://youtu.be/BtXFMV1Hi-w",
      dateOrder: "6/1/2017",
    },
    {
      title: "How to Disappear",
      date: "2017",
      role: "2nd AC/Sound Recordist/Sound Designer/Runner",
      description: "Short film",
      dateOrder: "7/1/2017",
    },
    {
      title: "By Design",
      date: "2017",
      role: "Sound recordist/2nd AC/Runner",
      description: "Short film",
      dateOrder: "8/1/2017",
    },
    {
      title: "Toast time",
      date: "2017",
      role: "DOP",
      description: "Short film",
      dateOrder: "9/1/2017",
    },
    {
      title: "Broken Minds",
      date: "2017",
      role: "Gaffer/2nd AC/Runner",
      description: "Short film",
      dateOrder: "1/2/2017",
    },
    {
      title: "Circular",
      date: "2017",
      role: "2nd AC/Gaffer/Runner",
      description: "Short film",
      dateOrder: "2/2/2017",
    },
    {
      title: "Stand Off",
      date: "2017",
      role: "2nd AC/Gaffer",
      description: "Short film",
      dateOrder: "3/2/2017",
    },
    {
      title: "Screened",
      date: "2017",
      role: "Sound Recordist/Gaffer",
      description: "Short film",
      dateOrder: "4/2/2017",
    },
    {
      title: "Hang in Hell",
      date: "2017",
      role: "DOP",
      description: "Short film",
      dateOrder: "5/2/2017",
    },
    {
      title: "I’m Sorry for your Loss",
      date: "2017",
      role: "2nd AC/Gaffer/Runner/Best Boy",
      description: "Short film",
      dateOrder: "6/2/2017",
    },
    {
      title: "The Bluebird",
      date: "2017",
      role: "1st AC/2nd AC/Production Assistant",
      description: "Short film",
      dateOrder: "7/2/2017",
    },
    {
      title: "Crimsons Suits",
      date: "2017",
      role: "2nd AC/ Sound Recordist/2nd Camera Operator",
      description: "Short film",
      dateOrder: "8/2/2017",
    },
    {
      title: "WTF TV PRESENTS: Sasha",
      date: "2017",
      role: "Director/Writer/Producer/Editor/Sound Recordist/Camera Operator/Actor",
      description: "Short film",
      dateOrder: "9/2/2017",
    },
    {
      title: "Lily",
      date: "2017",
      role: "Gaffer/1st AC",
      description: "Short film",
      dateOrder: "1/3/2017",
    },
    {
      title: "Sydney Film School AD",
      date: "2017",
      role: "2nd AC",
      description: "Commercial AD",
      dateOrder: "2/3/2017",
    },
    {
      title: "Memoir",
      date: "2017",
      role: "Gaffer",
      description: "Short film",
      dateOrder: "3/3/2017",
    },
    {
      title: "The Oracle",
      date: "2017",
      role: "1st AC/Best Boy/Stills Photographer",
      description: "Documentary short film",
      dateOrder: "4/3/2017",
    },
    {
      title: "Heart to Heart",
      date: "2017",
      role: "DOP",
      description: "Documentary short film",
      dateOrder: "5/3/2017",
    },
    {
      title: "The Wooden Sword",
      date: "2017",
      role: "Camera Operator",
      description: "Documentary short film",
      dateOrder: "6/3/2017",
    },
    {
      title: "Life's Symphony",
      date: "2017",
      role: "Camera operator",
      description: "Documentary short film",
      dateOrder: "7/3/2017",
    },
    {
      title: "Affixed",
      date: "2017",
      role: "3rd AC",
      description: "Short film",
      dateOrder: "1/3/2017",
    },
    {
      title: "Colour",
      date: "2017",
      role: "2nd AC",
      description: "Short film",
      dateOrder: "2/3/2017",
    },
    {
      title: "Strings",
      date: "2017",
      role: "2nd AC/ Grip",
      description: "Short film",
      video: "http link",
      dateOrder: "3/3/2017",
    },
    {
      title: "Out of my mind",
      date: "2017",
      role: "Camera Operator",
      description: "Short film",
      video: "http link",
      dateOrder: "1/1/2017",
    },
    {
      title: "Panopticon",
      date: "2017",
      role: "Best Boy/Runner",
      description: "Short film",
      video: "http link",
      dateOrder: "1/3/2017",
    },
    {
      title: "Veteran",
      date: "2017",
      role: "Grip/Gaffer/Runner",
      description: "Short film",
      video: "http link",
      dateOrder: "1/2/2017",
    },
    {
      title: "The Dilemma of Choice and Choosing Nothing Possible",
      date: "2017",
      role: "2nd AC",
      description: "Short film",
      video: "http link",
      dateOrder: "2/3/2017",
    },
    {
      title: "Out of my mind",
      date: "2017",
      role: "Camera Operator",
      description: "Short Film",
      dateOrder: "4/3/2017"
    }
  ]
}
